title:            Justin Moh
description:      Scribbles on Github Pages.
url:              http://justinmoh.github.io
signoff:          Justin Moh
disqus_shortname: justinmoh
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-64363852-2

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://justinmoh.github.io
    external:     true
  - name:         GitHub
    url:          http://github.com/justinmoh
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
